name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    - uses: gradle/actions/setup-gradle@v4
    - name: Unit-tests
      run: ./gradlew test
    - name: UI Tests [chrome]
      run: ./gradlew uitest_chrome -Dselenide.headless=true
    - name: UI Tests [firefox]
      run: ./gradlew uitest_firefox -Dselenide.headless=true
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-report
        retention-days: 28
        path: |
          **/build/reports
          **/build/test-results

  auto-merge-dependabot:
    name: 🤖 Auto merge dependabot PR
    timeout-minutes: 10
    needs: build
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: 🤖 Merge PR from dependabot
        uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          target: minor
          merge-method: rebase
